/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarrantyIndexRouteImport } from './routes/warranty.index'
import { Route as RepairsIndexRouteImport } from './routes/repairs.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as WarrantyIdRouteImport } from './routes/warranty.$id'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as RepairsQueueRouteImport } from './routes/repairs.queue'
import { Route as RepairsNewRouteImport } from './routes/repairs.new'
import { Route as RepairsIdRouteImport } from './routes/repairs.$id'
import { Route as InventoryScanRouteImport } from './routes/inventory.scan'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as RepairsIdReceiptRouteImport } from './routes/repairs.$id.receipt'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIndexRoute = WarrantyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarrantyRoute,
} as any)
const RepairsIndexRoute = RepairsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepairsRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const WarrantyIdRoute = WarrantyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WarrantyRoute,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsQueueRoute = RepairsQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => RepairsRoute,
} as any)
const RepairsNewRoute = RepairsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepairsRoute,
} as any)
const RepairsIdRoute = RepairsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepairsRoute,
} as any)
const InventoryScanRoute = InventoryScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const RepairsIdReceiptRoute = RepairsIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => RepairsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/logs': typeof LogsRoute
  '/repairs': typeof RepairsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/warranty': typeof WarrantyRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/scan': typeof InventoryScanRoute
  '/repairs/$id': typeof RepairsIdRouteWithChildren
  '/repairs/new': typeof RepairsNewRoute
  '/repairs/queue': typeof RepairsQueueRoute
  '/track/$code': typeof TrackCodeRoute
  '/warranty/$id': typeof WarrantyIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/repairs/': typeof RepairsIndexRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/repairs/$id/receipt': typeof RepairsIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/scan': typeof InventoryScanRoute
  '/repairs/$id': typeof RepairsIdRouteWithChildren
  '/repairs/new': typeof RepairsNewRoute
  '/repairs/queue': typeof RepairsQueueRoute
  '/track/$code': typeof TrackCodeRoute
  '/warranty/$id': typeof WarrantyIdRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/repairs': typeof RepairsIndexRoute
  '/warranty': typeof WarrantyIndexRoute
  '/repairs/$id/receipt': typeof RepairsIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/logs': typeof LogsRoute
  '/repairs': typeof RepairsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/warranty': typeof WarrantyRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/scan': typeof InventoryScanRoute
  '/repairs/$id': typeof RepairsIdRouteWithChildren
  '/repairs/new': typeof RepairsNewRoute
  '/repairs/queue': typeof RepairsQueueRoute
  '/track/$code': typeof TrackCodeRoute
  '/warranty/$id': typeof WarrantyIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/repairs/': typeof RepairsIndexRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/repairs/$id/receipt': typeof RepairsIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/logs'
    | '/repairs'
    | '/reports'
    | '/settings'
    | '/warranty'
    | '/customers/$id'
    | '/inventory/history'
    | '/inventory/scan'
    | '/repairs/$id'
    | '/repairs/new'
    | '/repairs/queue'
    | '/track/$code'
    | '/warranty/$id'
    | '/customers/'
    | '/inventory/'
    | '/repairs/'
    | '/warranty/'
    | '/repairs/$id/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/logs'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/inventory/history'
    | '/inventory/scan'
    | '/repairs/$id'
    | '/repairs/new'
    | '/repairs/queue'
    | '/track/$code'
    | '/warranty/$id'
    | '/customers'
    | '/inventory'
    | '/repairs'
    | '/warranty'
    | '/repairs/$id/receipt'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/logs'
    | '/repairs'
    | '/reports'
    | '/settings'
    | '/warranty'
    | '/customers/$id'
    | '/inventory/history'
    | '/inventory/scan'
    | '/repairs/$id'
    | '/repairs/new'
    | '/repairs/queue'
    | '/track/$code'
    | '/warranty/$id'
    | '/customers/'
    | '/inventory/'
    | '/repairs/'
    | '/warranty/'
    | '/repairs/$id/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LogsRoute: typeof LogsRoute
  RepairsRoute: typeof RepairsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WarrantyRoute: typeof WarrantyRouteWithChildren
  TrackCodeRoute: typeof TrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/': {
      id: '/warranty/'
      path: '/'
      fullPath: '/warranty/'
      preLoaderRoute: typeof WarrantyIndexRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/repairs/': {
      id: '/repairs/'
      path: '/'
      fullPath: '/repairs/'
      preLoaderRoute: typeof RepairsIndexRouteImport
      parentRoute: typeof RepairsRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/warranty/$id': {
      id: '/warranty/$id'
      path: '/$id'
      fullPath: '/warranty/$id'
      preLoaderRoute: typeof WarrantyIdRouteImport
      parentRoute: typeof WarrantyRoute
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs/queue': {
      id: '/repairs/queue'
      path: '/queue'
      fullPath: '/repairs/queue'
      preLoaderRoute: typeof RepairsQueueRouteImport
      parentRoute: typeof RepairsRoute
    }
    '/repairs/new': {
      id: '/repairs/new'
      path: '/new'
      fullPath: '/repairs/new'
      preLoaderRoute: typeof RepairsNewRouteImport
      parentRoute: typeof RepairsRoute
    }
    '/repairs/$id': {
      id: '/repairs/$id'
      path: '/$id'
      fullPath: '/repairs/$id'
      preLoaderRoute: typeof RepairsIdRouteImport
      parentRoute: typeof RepairsRoute
    }
    '/inventory/scan': {
      id: '/inventory/scan'
      path: '/scan'
      fullPath: '/inventory/scan'
      preLoaderRoute: typeof InventoryScanRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/repairs/$id/receipt': {
      id: '/repairs/$id/receipt'
      path: '/receipt'
      fullPath: '/repairs/$id/receipt'
      preLoaderRoute: typeof RepairsIdReceiptRouteImport
      parentRoute: typeof RepairsIdRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InventoryRouteChildren {
  InventoryHistoryRoute: typeof InventoryHistoryRoute
  InventoryScanRoute: typeof InventoryScanRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryHistoryRoute: InventoryHistoryRoute,
  InventoryScanRoute: InventoryScanRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface RepairsIdRouteChildren {
  RepairsIdReceiptRoute: typeof RepairsIdReceiptRoute
}

const RepairsIdRouteChildren: RepairsIdRouteChildren = {
  RepairsIdReceiptRoute: RepairsIdReceiptRoute,
}

const RepairsIdRouteWithChildren = RepairsIdRoute._addFileChildren(
  RepairsIdRouteChildren,
)

interface RepairsRouteChildren {
  RepairsIdRoute: typeof RepairsIdRouteWithChildren
  RepairsNewRoute: typeof RepairsNewRoute
  RepairsQueueRoute: typeof RepairsQueueRoute
  RepairsIndexRoute: typeof RepairsIndexRoute
}

const RepairsRouteChildren: RepairsRouteChildren = {
  RepairsIdRoute: RepairsIdRouteWithChildren,
  RepairsNewRoute: RepairsNewRoute,
  RepairsQueueRoute: RepairsQueueRoute,
  RepairsIndexRoute: RepairsIndexRoute,
}

const RepairsRouteWithChildren =
  RepairsRoute._addFileChildren(RepairsRouteChildren)

interface WarrantyRouteChildren {
  WarrantyIdRoute: typeof WarrantyIdRoute
  WarrantyIndexRoute: typeof WarrantyIndexRoute
}

const WarrantyRouteChildren: WarrantyRouteChildren = {
  WarrantyIdRoute: WarrantyIdRoute,
  WarrantyIndexRoute: WarrantyIndexRoute,
}

const WarrantyRouteWithChildren = WarrantyRoute._addFileChildren(
  WarrantyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LogsRoute: LogsRoute,
  RepairsRoute: RepairsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WarrantyRoute: WarrantyRouteWithChildren,
  TrackCodeRoute: TrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
